# Generated by Django 3.1.7 on 2021-06-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_property'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propertys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobno', models.CharField(max_length=12)),
                ('whtspno', models.CharField(max_length=12)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('sqft', models.IntegerField(blank=True)),
                ('list_date', models.DateTimeField(auto_now=True)),
                ('photo_main', models.ImageField(blank=True, upload_to='images')),
                ('photo1', models.ImageField(blank=True, upload_to='images')),
                ('photo2', models.ImageField(blank=True, upload_to='images')),
                ('status', models.CharField(choices=[('published', 'published'), ('blocked', 'blocked')], default='published', max_length=20)),
            ],
        ),
    ]
